tasks:
  - init: >
      npm install &&
      node ./gitpod-parcel-hmr-patch.js
  - command : npm start

ports:
  - port: 1234
    onOpen : open-preview
  - port: 3000
    onOpen : ignore

vscode:
  extensions:
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==